algoritmo "Trabalhando com tipos"

var
   palavra1, palavra2, palavra3: literal
   num1, num2, num3: inteiro
inicio
      Escreval("Palavra 1: ")
      Leia(palavra1)
      Escreval("Palavra 2: ")
      Leia(palavra2)
      Escreval("Numero 1: ")
      Leia(num1)
      Escreval("Numero 2: ")
      Leia(num2)
      palavra3 <- palavra1 + palavra2
      num3 <- num1 + num2
      EscrevaL(palavra3)
      EscrevaL(num3)

fimalgoritmo
