Algoritmo "Orientação a Objetos - herança"
//Este é um pseudo códdigo! O que está sendo escrito aqui,
//não tem suporte no Visualg, não roda!
tipo
//isso é um objeto
pessoa = registro
    nome: caractere
    rg: caractere
    dataNasc: inteiro
fimregistro
//PF herda de pessoa
pessoaFisica: pessoa
inicio
cpf: caractere
rg: caractere
fim

pessoaJuridica: pessoa
inicio
cnpj: caractere
ie: caractere
fim

var



Inicio

Fimalgoritmo