Algoritmo "Orientação a Objetos - herança"
//Este é um pseudo códdigo! O que está sendo escrito aqui,
//não tem suporte no Visualg, não roda!
tipo
//isso é um objeto
livro = registro
    nome: caractere
    isbn: caractere
    qtdPag: inteiro
fimregistro
var
   livro1 : livro
   livro2: livro
   
Inicio
   livro1.nome <- "Senhor dos Anéis"
   livro2.nome <- "Harry Potter"
   
   se livro1.nome = livro2.nome entao


Fimalgoritmo