Algoritmo "Orientação a Objetos"

tipo
//isso é um objeto
cadastroCliente = registro
    nome: caractere
    rg: caractere
    idade: inteiro
fimregistro

Var

cliente1: cadastroCliente

Inicio

Escreval("Digite seu nome: ")
leia(cliente1.nome)
Escreval("Digite seu RG: ")
leia(cliente1.rg)
Escreval("Digite sua idade: ")
leia(cliente1.idade)

Escreval("Nome: ",cliente1.nome," RG: ",cliente1.rg," Idade: ",cliente1.idade)


Fimalgoritmo